package surface

var MCPDaemonRoutes = []string{
	"POST /mcp",
	"GET /mcp",
	"DELETE /mcp",
	"GET /ws/canvas",
	"GET /files/*",
	"GET /health",
}

var WebRouteSections = []RouteSection{
	{
		Title: "Public pages",
		Routes: []string{
			"GET /",
			"GET /canvas",
			"GET /capture",
		},
	},
	{
		Title: "Auth and setup",
		Routes: []string{
			"GET /api/setup",
			"POST /api/login",
			"POST /api/cli/login",
			"POST /api/logout",
			"GET /api/google/auth",
			"GET /api/google/callback",
		},
	},
	{
		Title: "Runtime and chat session management",
		Routes: []string{
			"GET /api/runtime",
			"PATCH /api/runtime/preferences",
			"POST /api/runtime/yolo",
			"POST /api/runtime/disclaimer-ack",
			"GET /api/live-policy",
			"POST /api/live-policy",
			"GET /api/plugins",
			"POST /api/plugins/meeting-partner/decide",
			"GET /api/extensions",
			"POST /api/extensions/commands/{command_id}",
			"GET /api/runtime/workspaces",
			"GET /api/runtime/workspaces/activity",
			"GET /api/runtime/workspace-presets",
			"POST /api/runtime/workspace-presets/{preset_id}/activate",
			"POST /api/runtime/workspaces",
			"POST /api/runtime/workspaces/{workspace_id}/activate",
			"POST /api/runtime/workspaces/{workspace_id}/persist",
			"POST /api/runtime/workspaces/{workspace_id}/discard",
			"POST /api/runtime/workspaces/{workspace_id}/chat-model",
			"GET /api/runtime/workspaces/{workspace_id}/snapshot",
			"GET /api/runtime/workspaces/{workspace_id}/welcome",
			"GET /api/workspaces/{workspace_id}/files",
			"GET /api/workspaces/{workspace_id}/markdown-link/resolve",
			"GET /api/workspaces/{workspace_id}/markdown-link/file",
			"GET /api/workspaces/{workspace_id}/companion/config",
			"PUT /api/workspaces/{workspace_id}/companion/config",
			"GET /api/workspaces/{workspace_id}/companion/state",
			"GET /api/workspaces/{workspace_id}/transcript",
			"GET /api/workspaces/{workspace_id}/summary",
			"GET /api/workspaces/{workspace_id}/references",
			"POST /api/workspaces/{workspace_id}/meeting/finalize",
			"GET /api/workspaces/{workspace_id}/meeting-items",
			"POST /api/workspaces/{workspace_id}/meeting-items",
			"POST /api/participant/document-follow/decide",
			"POST /api/chat/sessions",
			"GET /api/chat/sessions/{session_id}/history",
			"GET /api/chat/sessions/{session_id}/activity",
			"POST /api/chat/sessions/{session_id}/messages",
			"POST /api/chat/sessions/{session_id}/commands",
			"POST /api/chat/sessions/{session_id}/cancel",
			"GET /api/chat/sessions/{session_id}/dictation",
			"DELETE /api/chat/sessions/{session_id}/dictation",
			"POST /api/chat/sessions/{session_id}/dictation/start",
			"POST /api/chat/sessions/{session_id}/dictation/append",
			"PUT /api/chat/sessions/{session_id}/dictation/draft",
			"POST /api/ink/submit",
			"POST /api/review/submit",
			"POST /api/scan/upload",
			"POST /api/scan/confirm",
			"POST /api/bugs/report",
			"POST /api/push/register",
			"GET /api/mail/accounts",
			"POST /api/mail/drafts",
			"POST /api/mail/drafts/reply",
			"POST /api/mail/drafts/reply-all",
			"POST /api/mail/drafts/forward",
			"GET /api/mail/drafts/{artifact_id}",
			"PUT /api/mail/drafts/{artifact_id}",
			"POST /api/mail/drafts/{artifact_id}/send",
			"POST /api/mail/drafts/{artifact_id}/polish",
			"POST /api/text/polish",
			"GET /api/external-accounts/{account_id}/mail/labels",
			"GET /api/external-accounts/{account_id}/mail/messages",
			"GET /api/external-accounts/{account_id}/mail/messages/{message_id}",
			"GET /api/external-accounts/{account_id}/mail/messages/{message_id}/attachments/{attachment_id}",
			"POST /api/external-accounts/{account_id}/mail/actions",
			"GET /api/external-accounts/{account_id}/mail-rules",
			"POST /api/external-accounts/{account_id}/mail-rules",
			"PUT /api/external-accounts/{account_id}/mail-rules/{rule_id}",
			"DELETE /api/external-accounts/{account_id}/mail-rules/{rule_id}",
			"POST /api/external-accounts/{account_id}/mail-triage/preview",
			"GET /api/external-accounts/{account_id}/mail-triage/report",
			"POST /api/external-accounts/{account_id}/mail-triage/evaluate",
			"POST /api/external-accounts/{account_id}/mail-triage/arm",
			"POST /api/external-accounts/{account_id}/mail-triage/apply",
			"GET /api/external-accounts/{account_id}/mail-triage/manual/reviews",
			"POST /api/external-accounts/{account_id}/mail-triage/manual/reviews",
			"POST /api/external-accounts/{account_id}/mail-triage/manual/reviews/{review_id}/undo",
			"GET /api/external-accounts/{account_id}/mail-server-filters",
			"POST /api/external-accounts/{account_id}/mail-server-filters",
			"PUT /api/external-accounts/{account_id}/mail-server-filters/{filter_id}",
			"DELETE /api/external-accounts/{account_id}/mail-server-filters/{filter_id}",
		},
	},
	{
		Title: "Domain model API",
		Routes: []string{
			"GET /api/workspaces",
			"GET /api/workspaces/busy",
			"GET /api/workspace/focus",
			"GET /api/watches",
			"POST /api/workspaces",
			"POST /api/workspace/focus",
			"GET /api/workspaces/{workspace_id}",
			"PUT /api/workspaces/{workspace_id}",
			"GET /api/workspaces/{workspace_id}/watch",
			"POST /api/workspaces/{workspace_id}/watch",
			"DELETE /api/workspaces/{workspace_id}/watch",
			"DELETE /api/workspace/focus",
			"DELETE /api/workspaces/{workspace_id}",
			"GET /api/time-entries",
			"GET /api/time-entries/summary",
			"POST /api/time-entries/stamp-in",
			"POST /api/time-entries/stamp-out",
			"GET /api/spheres/{sphere}/accounts",
			"POST /api/spheres/{sphere}/accounts",
			"DELETE /api/spheres/{sphere}/accounts/{account_id}",
			"GET /api/external-accounts",
			"POST /api/external-accounts",
			"PUT /api/external-accounts/{account_id}",
			"DELETE /api/external-accounts/{account_id}",
			"GET /api/container-mappings",
			"POST /api/container-mappings",
			"DELETE /api/container-mappings/{mapping_id}",
			"GET /api/actors",
			"POST /api/actors",
			"GET /api/actors/{actor_id}",
			"DELETE /api/actors/{actor_id}",
			"GET /api/labels",
			"POST /api/dialogue/diagnostics",
			"GET /api/artifacts",
			"POST /api/artifacts",
			"GET /api/artifacts/taxonomy",
			"GET /api/artifacts/{artifact_id}",
			"POST /api/artifacts/{artifact_id}/extract-figures",
			"POST /api/artifacts/{artifact_id}/materialize",
			"GET /api/artifacts/{artifact_id}/items",
			"DELETE /api/artifacts/{artifact_id}",
			"GET /api/batches",
			"GET /api/batches/{batch_id}",
			"GET /api/batches/{batch_id}/artifact",
			"GET /api/items",
			"POST /api/items",
			"GET /api/items/inbox",
			"GET /api/items/next",
			"GET /api/items/waiting",
			"GET /api/items/deferred",
			"GET /api/items/someday",
			"GET /api/items/review",
			"GET /api/items/done",
			"GET /api/items/counts",
			"POST /api/items/sync/github",
			"POST /api/items/sync/github/reviews",
			"GET /api/items/{item_id}",
			"GET /api/items/{item_id}/artifacts",
			"POST /api/items/{item_id}/artifacts",
			"DELETE /api/items/{item_id}/artifacts/{artifact_id}",
			"PUT /api/items/{item_id}",
			"DELETE /api/items/{item_id}",
			"PUT /api/items/{item_id}/state",
			"PUT /api/items/{item_id}/assign",
			"PUT /api/items/{item_id}/unassign",
			"PUT /api/items/{item_id}/complete",
			"PUT /api/items/{item_id}/workspace",
			"POST /api/items/{item_id}/project-item-link",
			"POST /api/items/{item_id}/dispatch-review",
			"POST /api/items/{item_id}/triage",
			"GET /api/items/{item_id}/print",
		},
	},
	{
		Title: "Canvas/files",
		Routes: []string{
			"GET /api/canvas/{session_id}/snapshot",
			"GET /api/files/{session_id}/*",
		},
	},
	{
		Title: "Websocket routes",
		Routes: []string{
			"GET /ws/chat/{session_id}",
			"GET /ws/turn/{session_id}",
			"GET /ws/canvas/{session_id}",
		},
	},
	{
		Title: "Participant and STT APIs",
		Routes: []string{
			"GET /api/participant/config",
			"PUT /api/participant/config",
			"GET /api/participant/status",
			"GET /api/participant/sessions",
			"GET /api/participant/sessions/{id}/transcript",
			"GET /api/participant/sessions/{id}/search",
			"GET /api/participant/sessions/{id}/export",
			"POST /api/stt/transcribe",
			"GET /api/stt/config",
			"PUT /api/stt/config",
			"GET /api/stt/replacements",
			"PUT /api/stt/replacements",
			"GET /api/hotword/status",
			"GET /api/hotword/catalog",
			"POST /api/hotword/catalog/download",
			"GET /api/hotword/train/recordings",
			"POST /api/hotword/train/recordings",
			"DELETE /api/hotword/train/recordings/{recording_id}",
			"GET /api/hotword/train/recordings/{recording_id}/audio",
			"GET /api/hotword/train/config",
			"PUT /api/hotword/train/config",
			"POST /api/hotword/train/generate",
			"GET /api/hotword/train/generate/status",
			"GET /api/hotword/train/feedback",
			"POST /api/hotword/train/feedback",
			"POST /api/hotword/train/start",
			"POST /api/hotword/train/pipeline",
			"GET /api/hotword/train/status",
			"POST /api/hotword/train/deploy",
			"GET /api/hotword/train/models",
		},
	},
}
